name: CD Test

on:
  push:
    branches:
      - proddddddd

jobs:
  deployed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload app to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          source: "out"
          target: "/var/www/httpdocs"
