name: CI test

on:
  workflow_dispatch:

  schedule:
    - cron: '0 3 * * 1'

  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop
      - prod

jobs:
  renovate:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: write
      pull-requests: write
      issues: write
    container:
      image: renovate/renovate:latest

    steps:
      - name: Run Renovate
        env:
          RENOVATE_PLATFORM: github
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN || github.token }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        run: renovate

  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Install checkout
        uses: actions/checkout@v7

      - name: Check Docker version
        run: |
          docker -v
          docker compose version

      - name: install dependencies
        run: docker compose run --rm node npm ci

      - name: lint
        run: docker compose run --rm node npm run lint

      - name: build app
        run: docker compose run --rm node npm run build

      - name: stop docker
        if: always()
        run: docker compose down
