name: CI test

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Install checkout
        uses: actions/checkout@v7

      - name: Check Docker version
        run: |
          docker -v
          docker compose version

      - name: docker up
        run: docker compose up -d

      - name: install dependencies
        run: docker compose
